Repository google/go-github, pull requests merged in 2018-07, with the labels that each got.

#901 Add example app for creating commit and PR
  example/commitpr/main.go
Labels: cla: yes

#933 Add find installation by org, repo and user API
  github/apps.go
  github/apps_test.go
Labels: NeedsReview, cla: yes

#947 Update the transfer repository request to use the correct json name
  github/repos.go
Labels: cla: yes

#951 Make error return style in repos_hooks.go consistent
  github/repos_hooks.go
Labels: cla: yes

#939 Remove custom media type for license api (#813)
  github/github.go
  github/licenses.go
  github/licenses_test.go
  github/repos.go
  github/repos_test.go
Labels: cla: yes

#952 add created/updated at fields to Installation type
  github/apps.go
  github/apps_test.go
  github/github-accessors.go
Labels: cla: yes

#950 Fix InReplyToID JSON tag for PullRequestComment
  github/pulls_comments.go
Labels: cla: yes

#955 Remove unnecessary index.html from a #compare-two-commits url
  github/repos_commits.go
Labels: cla: yes

#953 Project card archiving
  github/github-accessors.go
  github/projects.go
  github/projects_test.go
Labels: NeedsReview, cla: yes

#914 Add checks api
  github/activity_events.go
  github/checks.go
  github/checks_test.go
  github/event_types.go
  github/github-accessors.go
  github/github.go
  github/messages.go
  github/messages_test.go
Labels: NeedsReview, cla: no

#957 Add IssueTemplate and PullRequestTemplate in ReposCommunityHealth struct
  github/github-accessors.go
  github/repos_community_health.go
Labels: cla: yes

#927 support for user migration API (#918)
  AUTHORS
  example/migrations/main.go
  github/github-accessors.go
  github/migrations_user.go
  github/migrations_user_test.go
Labels: NeedsReview, cla: yes

#954 fix go vet error with go1.11
  github/misc_test.go
  github/repos_contents_test.go
Labels: cla: yes

#928 Removed mediaTypeMarketplacePreview
  github/apps_marketplace.go
  github/apps_marketplace_test.go
  github/github.go
Labels: NeedsReview, cla: yes

#960 Remove redundant dereference of time.Time
  github/timestamp.go
Labels: cla: yes
