Repository google/go-github, pull requests merged in 2018-08, with the labels that each got.

#923 Add Truncated field to Tree
  github/git_trees.go
  github/git_trees_test.go
  github/github-accessors.go
Labels: NeedsReview, cla: yes

#961 provide more clear contributing details in README.md
  README.md
Labels: cla: yes

#938 Add UpdateRequiredStatusChecks function
  github/github-accessors.go
  github/repos.go
  github/repos_test.go
Labels: NeedsReview, cla: yes

#945 Add APIs for pre-receive hooks
  github/github-accessors.go
  github/github.go
  github/repos_prereceive_hooks.go
  github/repos_prereceive_hooks_test.go
Labels: NeedsReview, cla: yes

#962 fix named consts
  github/activity_notifications_test.go
  github/apps_test.go
  github/gists_test.go
  github/github_test.go
  github/orgs_members_test.go
  github/orgs_teams_test.go
  github/repos_community_health_test.go
  github/repos_stats_test.go
  github/strings_test.go
  github/teams_discussion_comments_test.go
  github/teams_discussions_test.go
  github/timestamp_test.go
Labels: cla: yes

#965 Installation: Use *Timestamp instead of *time.Time for the benefit of InstallationEvent
  github/apps.go
  github/apps_test.go
  github/github-accessors.go
Labels: cla: yes

#967 Remove support for Go 1.7
  .travis.yml
  README.md
Labels: cla: yes

#966 Use PathEscape on search query instead of QueryEscape
  github/search.go
  github/search_test.go
Labels: cla: yes

#910 Added support for preview Lock Reason (#828)
  github/github-accessors.go
  github/github.go
  github/issues.go
  github/issues_events.go
  github/issues_test.go
  github/pulls.go
  github/pulls_test.go
Labels: NeedsReview, cla: no

#972 Move Teams API off Organizations
  github/examples_test.go
  github/github-accessors.go
  github/orgs_teams.go
  github/orgs_teams_test.go
  github/teams.go
  github/teams_discussion_comments.go
  github/teams_discussion_comments_test.go
  github/teams_discussions.go
  github/teams_discussions_test.go
  github/teams_members.go
  github/teams_members_test.go
  github/teams_test.go
Labels: cla: no

#973 Support Preview Hovercard API
  github/github-accessors.go
  github/github.go
  github/users.go
  github/users_test.go
Labels: cla: no

#880 Add RequiredApprovingReviewCount to PullRequestReviewsEnforcement
  github/github.go
  github/repos.go
  github/repos_test.go
  test/integration/repos_test.go
Labels: NeedsReview, cla: yes

#871 Update orgs_members.go
  github/orgs_members.go
Labels: cla: no

#971 Update PushEventRepository.Owner to be of type User [breaking change]
  github/event_types.go
  github/github-accessors.go
Labels: NeedsReview, cla: yes

#969 projects: Add missing fields to struct
  github/github-accessors.go
  github/orgs_projects_test.go
  github/projects.go
  github/projects_test.go
  github/repos_projects_test.go
Labels: cla: yes, waiting for reply

#979 Add FindRepositoryInstallationByID to AppsService
  github/apps.go
  github/apps_test.go
Labels: cla: yes

#985 Introduce go modules
  .travis.yml
  README.md
  example/appengine/app.go
  example/basicauth/main.go
  example/commitpr/main.go
  example/migrations/main.go
  example/newrepo/main.go
  example/simple/main.go
  github/examples_test.go
  github/projects_test.go
  go.mod
  go.sum
  test/fields/fields.go
Labels: cla: yes

#978 Fix RequestCheckSuite
  github/checks.go
  github/checks_test.go
Labels: cla: yes, lgtm

#977 Fixes wrong Accept media type that was causing a 500
  github/issues.go
  github/issues_test.go
Labels: cla: yes

#982 add support for Team Reactions API
  github/github-accessors.go
  github/reactions.go
  github/reactions_test.go
  github/teams_discussion_comments.go
  github/teams_discussions.go
Labels: cla: yes
