Repository google/go-github, pull requests merged in 2021-12, with the labels that each got.

#2176 Adds test-cases for JSON resources marshaling
  github/repos_test.go
Labels: cla: yes, hacktoberfest-accepted

#2111 ProjectOptions (public to private) & Project struct (org related fields) fixes
  github/github-accessors.go
  github/github-accessors_test.go
  github/github-stringify_test.go
  github/projects.go
  github/projects_test.go
Labels: cla: yes, Breaking API Change

#2210 Add CodeScanningService.ListAnalysesForRepo and CodeScanningService.GetAnalysis
  github/code-scanning.go
  github/code-scanning_test.go
  github/github-accessors.go
  github/github-accessors_test.go
Labels: cla: yes

#2092 Handle protection status errors for unprotected branches
  github/repos.go
  github/repos_test.go
Labels: cla: yes

#2109 Update GitHub Pages API to add new response parameters
  github/github-accessors.go
  github/github-accessors_test.go
  github/repos_pages.go
  github/repos_pages_test.go
Labels: cla: yes

#2216 Add BranchProtectionRuleEvent Installation field
  github/event_types.go
  github/github-accessors.go
  github/github-accessors_test.go
  scrape/testdata/access-restrictions-disabled.html
  scrape/testdata/access-restrictions-enabled.html
Labels: cla: yes

#2218 Fix since+page pagination bug
  github/github.go
  github/github_test.go
Labels: cla: yes

#2219 build: upgrade `go` directive in `go.mod` to 1.17
  go.mod
Labels: cla: yes

#2217 Add support for External Groups
  github/github-accessors.go
  github/github-accessors_test.go
  github/teams.go
  github/teams_test.go
Labels: cla: yes
