Repository google/go-github, pull requests merged in 2021-04, with the labels that each got.

#1842 Update document links of event types
  github/event_types.go
  github/pulls.go
Labels: cla: yes

#1827 Fix invalid response and rename ListPlanAccountsForAccount (fixes #1270)
  github/apps_marketplace.go
  github/apps_marketplace_test.go
  github/github-accessors.go
  github/github-accessors_test.go
Labels: Breaking API Change, cla: yes

#1836 Support numeric public key ids for actions
  github/actions_secrets.go
  github/actions_secrets_test.go
Labels: cla: yes

#1844 Add support for pull_request_target webhook event
  github/event.go
  github/event_types.go
  github/github-accessors.go
  github/github-accessors_test.go
  github/messages.go
  github/messages_test.go
Labels: cla: yes

#1847 Add support for environments and environment secrets
  github/actions_secrets.go
  github/actions_secrets_test.go
  github/github-accessors.go
  github/github-accessors_test.go
  github/repos_environments.go
  github/repos_environments_test.go
Labels: cla: yes

#1850 Add Support For Millisecond Timestamps
  github/enterprise_audit_log_test.go
  github/orgs_audit_log_test.go
  github/timestamp.go
  github/timestamp_test.go
Labels: cla: yes

#1852 Bump version of go-github library
  README.md
  example/appengine/app.go
  example/basicauth/main.go
  example/commitpr/main.go
  example/migrations/main.go
  example/newrepo/main.go
  example/newreposecret/go.mod
  example/newreposecret/main.go
  example/simple/main.go
  example/tokenauth/main.go
  example/topics/main.go
  github/doc.go
  github/examples_test.go
  go.mod
  test/fields/fields.go
  test/integration/activity_test.go
  test/integration/authorizations_test.go
  test/integration/github_test.go
  test/integration/repos_test.go
  test/integration/users_test.go
Labels: cla: yes

#1853 Improve tokenauth example as debugging tool
  example/tokenauth/main.go
Labels: cla: yes

#1854 Update error handling as per Go 1.13 guidelines
  README.md
  github/github.go
  github/github_test.go
Labels: cla: yes

#1856 feat: support new release discussions feature
  github/github-accessors.go
  github/github-accessors_test.go
  github/github-stringify_test.go
  github/repos_releases.go
  github/repos_releases_test.go
Labels: cla: yes

#1857 Revert "Fix: Remove Sort & Direction Fields From IssueListCommentsOptions"
  github/github-accessors.go
  github/github-accessors_test.go
  github/issues_comments.go
  github/issues_comments_test.go
Labels: Breaking API Change, bug, cla: yes

#1860 Apps-Service: Add baptiste-preview to ListRepos and ListUserRepos
  github/apps_installation.go
  github/apps_installation_test.go
Labels: cla: yes

#1858 Remove obsolete apps manifest preview custom header
  github/apps_manifest.go
  github/apps_manifest_test.go
Labels: cla: yes
