Repository google/go-github, pull requests merged in 2022-12, with the labels that each got.

#2578 Add support for repository actions access level / permission
  github/github-accessors.go
  github/github-accessors_test.go
  github/repos_actions_access.go
  github/repos_actions_access_test.go
Labels: NeedsReview

#2606 Fix JSON protection unmarshal error
  github/github-accessors.go
  github/github-accessors_test.go
  github/repos.go
Labels: bug, Breaking API Change

#2597 Change actions billing structs to maps
  github/actions_workflow_runs.go
  github/actions_workflow_runs_test.go
  github/actions_workflows.go
  github/actions_workflows_test.go
  github/billing.go
  github/billing_test.go
  github/github-accessors.go
  github/github-accessors_test.go
Labels: Breaking API Change
