Repository google/go-github, pull requests merged in 2022-08, with the labels that each got.

#2432 Add BypassPullRequestAllowances field
  github/github-accessors.go
  github/github-accessors_test.go
  github/repos.go
  github/repos_test.go
Labels: NeedsReview

#2422 Add 'pending_deployments' endpoint support (#2421)
  github/actions_workflow_runs.go
  github/actions_workflow_runs_test.go
Labels: NeedsReview

#2429 Add LFS control
  github/repos_lfs.go
  github/repos_lfs_test.go
Labels: NeedsReview

#2424 Add tag protection
  example/tagprotection/main.go
  github/github-accessors.go
  github/github-accessors_test.go
  github/repos_tags.go
  github/repos_tags_test.go
Labels: NeedsReview

#2388 Add TextMatch custom header to other search type custom headers
  github/search.go
  github/search_test.go
Labels: NeedsReview

#2392 Add support for parsing code_scanning_alerts in webhooks
  github/event.go
  github/messages.go
  github/messages_test.go
  github/repos_hooks_deliveries_test.go
Labels: NeedsReview

#2401 Change DependabotSecretsSelectedRepoIDs to []string
  github/actions_secrets.go
  github/dependabot_secrets.go
  github/dependabot_secrets_test.go
Labels: NeedsReview, Breaking API Change

#2403 Include the version of `go-github` in `User-Agent` headers sent to the GitHub API
  CONTRIBUTING.md
  github/github.go
  github/github_test.go
Labels: NeedsReview

#2397 Add hooks support for WebSub (formerly PubSubHubbub) protocol
  github/github.go
  github/github_test.go
  github/repos_hooks.go
  github/repos_hooks_test.go
Labels: waiting for reply

#2417 Add ListOptions for listing user migrations
  example/migrations/main.go
  github/migrations_user.go
  github/migrations_user_test.go
Labels: Breaking API Change
