Repository google/go-github, pull requests merged in 2023-12, with the labels that each got.

#3023 Fix broken CreateOrUpdateRepoCustomPropertyValues
  github/orgs_properties.go
  github/orgs_properties_test.go
Labels: bug, Breaking API Change

#3017 Remove ambiguous fields from AuditEntry
  github/enterprise_audit_log_test.go
  github/github-accessors.go
  github/github-accessors_test.go
  github/github_test.go
  github/orgs_audit_log.go
  github/orgs_audit_log_test.go
  test/integration/audit_log_test.go
Labels: Breaking API Change

#2973 Add Copilot endpoints
  github/copilot.go
  github/copilot_test.go
  github/github-accessors.go
  github/github-accessors_test.go
  github/github.go
Labels: NeedsReview
