Repository google/go-github, pull requests merged in 2024-02, with the labels that each got.

#3050 Add support for deployment protection rules
  github/github-accessors.go
  github/github-accessors_test.go
  github/repos_deployment_protection_rules.go
  github/repos_deployment_protection_rules_test.go
Labels: NeedsReview

#3060 Add ListWorkflowJobsAttempt method to ActionsService
  github/actions_workflow_jobs.go
  github/actions_workflow_jobs_test.go
Labels: NeedsReview

#3070 Turn `RequiredStatusChecks` `Checks` and `Contexts` into pointers
  github/github-accessors.go
  github/github-accessors_test.go
  github/repos.go
  github/repos_test.go
  test/integration/repos_test.go
Labels: Breaking API Change

#3073 feat!: Change Hook Config field from map to *HookConfig
  github/event_types_test.go
  github/github-accessors.go
  github/github-accessors_test.go
  github/github-stringify_test.go
  github/orgs_audit_log.go
  github/repos_hooks.go
  github/repos_hooks_configuration.go
  github/repos_hooks_test.go
Labels: NeedsReview, Breaking API Change
