Repository google/go-github, pull requests merged in 2025-01, with the labels that each got.

#3423 fix: Relax go directive in go.mod to 1.22.0
  .github/workflows/tests.yml
  README.md
  example/go.mod
  example/go.sum
  example/newreposecretwithlibsodium/go.mod
  example/verifyartifact/main.go
  go.mod
  scrape/go.mod
  scrape/go.sum
  tools/go.mod
  tools/go.sum
Labels: NeedsReview

#3444 fix!: Typo in field names in the CheckSuite struct
  github/checks.go
  github/checks_test.go
  github/github-accessors.go
  github/github-accessors_test.go
  github/github-stringify_test.go
Labels: NeedsReview, Breaking API Change

#3445 fix!: Typo in field names in the PullStats struct
  github/admin_stats.go
  github/admin_stats_test.go
  github/github-accessors.go
  github/github-accessors_test.go
  github/github-stringify_test.go
Labels: NeedsReview, Breaking API Change

#3446 refactor!: Do not capitalize error strings
  .golangci.yml
  example/codespaces/newreposecretwithxcrypto/main.go
  example/codespaces/newusersecretwithxcrypto/main.go
  example/newreposecretwithlibsodium/main.go
  example/newreposecretwithxcrypto/main.go
  github/github.go
  github/github_test.go
  github/repos_rules.go
Labels: Breaking API Change

#3430 fix!: Refactor the repository ruleset code
  github/enterprise_rules.go
  github/enterprise_rules_test.go
  github/event_types.go
  github/event_types_test.go
  github/github-accessors.go
  github/github-accessors_test.go
  github/github.go
  github/orgs_rules.go
  github/orgs_rules_test.go
  github/repos_rules.go
  github/repos_rules_test.go
  github/rules.go
  github/rules_test.go
Labels: Breaking API Change

#3447 chore!: Add `sliceofpointers` custom linter
  .custom-gcl.yml
  .gitignore
  .golangci.yml
  github/codespaces_secrets_test.go
  github/github.go
  github/strings_test.go
  scrape/apps.go
  scrape/apps_test.go
  scrape/forms.go
  scrape/forms_test.go
  script/lint.sh
  tools/sliceofpointers/go.mod
  tools/sliceofpointers/go.sum
  tools/sliceofpointers/sliceofpointers.go
  tools/sliceofpointers/sliceofpointers_test.go
  tools/sliceofpointers/testdata/src/has-warnings/main.go
  tools/sliceofpointers/testdata/src/no-warnings/main.go
Labels: Breaking API Change

#3453 Extend `Rate` and Rate Limiting with `X-Ratelimit-Used` and `X-Ratelimit-Resource` headers
  github/github-stringify_test.go
  github/github.go
  github/github_test.go
  github/rate_limit.go
  github/rate_limit_test.go
Labels: NeedsReview
